#index:
#    path: /
#    controller: App\Controller\DefaultController::index
register:
  path: /register
  controller: App\Controller\AuthController::register
  methods: POST

api_login_check:
  path: /api/login_check
  controller: App\Controller\AuthController::getTokenUser

test:
  path: /api/test
  controller: App\Controller\ApiController::test

